# Generated by Django 4.1.2 on 2022-10-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['time_created'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
