# Generated by Django 4.1.2 on 2022-10-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0005_alter_events_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категории товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Роли', 'verbose_name_plural': 'Роли'},
        ),
    ]
