# Generated by Django 4.1.2 on 2022-10-08 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0007_guilds_alter_taskfilters_options_users_guild'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vtb.guilds')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vtb.users')),
            ],
        ),
    ]
