# Generated by Django 4.1.2 on 2022-10-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0008_guildusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='guild',
        ),
    ]
