# Generated by Django 4.1.2 on 2022-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0010_rename_user_id_guildusers_guild_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='privateKey',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='publicKey',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
