# Generated by Django 4.1.2 on 2022-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0012_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
