# Generated by Django 4.1.2 on 2022-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0013_goods_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
