# Generated by Django 4.1.2 on 2022-10-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0014_inventory_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='min_exp',
        ),
    ]
