# Generated by Django 4.1.2 on 2022-10-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0016_remove_tasks_filter_remove_tasks_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='reward',
        ),
    ]
