# Generated by Django 4.1.2 on 2022-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0017_remove_tasks_description_remove_tasks_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='reward',
            field=models.IntegerField(null=True),
        ),
    ]
