# Generated by Django 4.1.2 on 2022-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0019_tasks_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guilds',
            options={'verbose_name': 'Гальдии', 'verbose_name_plural': 'Гильдии'},
        ),
        migrations.AddField(
            model_name='guilds',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
