# Generated by Django 4.1.2 on 2022-10-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0020_alter_guilds_options_guilds_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
