# Generated by Django 4.1.2 on 2022-10-09 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0021_guilds_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='for_guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vtb.guilds'),
        ),
    ]
