# Generated by Django 4.1.2 on 2022-10-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtb', '0022_tasks_for_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='guilds',
            name='guildName',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='taskfilters',
            name='filter',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
